### ISSUE TITLE
WPG calculator in SimEx-Lite

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/SimEx-Lite#6]
- [x] Calculator test
- [x] WavefrontData test
- [x] Modify `data_to_return` in `BaseData` to accept extra data.

**Comment by JunCEEE** [comment]
```
Traceback (most recent call last):
  File "test_GaussianSourceCalculator.py", line 10, in <module>
    data_out = calculator.backengine()
  File "/gpfs/exfel/data/user/juncheng/SimExLite/SimExLite/SourceCalculators/GaussianSourceCalculator.py", line 193, in backengine
    wavefront.store_hdf5(filename)
  File "/home/juncheng/GPFS/exfel/data/user/juncheng/WPG/wpg/wavefront.py", line 175, in store_hdf5
    self._store_attributes(file_name)
  File "/home/juncheng/GPFS/exfel/data/user/juncheng/WPG/wpg/wavefront.py", line 163, in _store_attributes
    h5f[wff.glossary_name].attrs[k] = v
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/gpfs/exfel/data/user/juncheng/miniconda3/envs/simex-lite-dev/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/gpfs/exfel/data/user/juncheng/miniconda3/envs/simex-lite-dev/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 196, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 50, in h5py.h5a.create
RuntimeError: Unable to create attribute (no write intent on file)
```

**Comment by JunCEEE** [comment]
Probably we can set up a `calculator.check_env` function to check if the basic environment for the calculator is satisfied.

**Comment by JunCEEE** [comment]
Should we allow the calculator to return a data object mapping to a python class: e.g. `Wavefront` defined in `wpg`?

A `BaseObjectMapping` class could be created for this purpose.

**Comment by CFGrote** [comment]
Regarding h5py: @buzmakov and @samoylv tell me that there is a new WPG release that should fix the above error, @JunCEEE can you follow up?
